config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :loai_thuocs
  resources :nccs
  resources :sxes
  resources :thuocs

  get '/',to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loai_thuoc.rb
class LoaiThuoc < ApplicationRecord
end

app/models/ncc.rb
class Ncc < ApplicationRecord
end

app/models/sx.rb
class Sx < ApplicationRecord
end

app/models/thuoc.rb
class Thuoc < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/loai_thuocs_controller.rb
class LoaiThuocsController < ApplicationController
  before_action :set_loai_thuoc, only: %i[ show edit update destroy ]

  # GET /loai_thuocs or /loai_thuocs.json
  def index
    @loai_thuocs = LoaiThuoc.all
  end

  # GET /loai_thuocs/1 or /loai_thuocs/1.json
  def show
  end

  # GET /loai_thuocs/new
  def new
    @loai_thuoc = LoaiThuoc.new
  end

  # GET /loai_thuocs/1/edit
  def edit
  end

  # POST /loai_thuocs or /loai_thuocs.json
  def create
    @loai_thuoc = LoaiThuoc.new(loai_thuoc_params)

    respond_to do |format|
      if @loai_thuoc.save
        format.html { redirect_to @loai_thuoc, notice: "Loai thuoc was successfully created." }
        format.json { render :show, status: :created, location: @loai_thuoc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loai_thuoc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loai_thuocs/1 or /loai_thuocs/1.json
  def update
    respond_to do |format|
      if @loai_thuoc.update(loai_thuoc_params)
        format.html { redirect_to @loai_thuoc, notice: "Loai thuoc was successfully updated." }
        format.json { render :show, status: :ok, location: @loai_thuoc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loai_thuoc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loai_thuocs/1 or /loai_thuocs/1.json
  def destroy
    @loai_thuoc.destroy
    respond_to do |format|
      format.html { redirect_to loai_thuocs_url, notice: "Loai thuoc was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loai_thuoc
      @loai_thuoc = LoaiThuoc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loai_thuoc_params
      params.require(:loai_thuoc).permit(:maloai, :tenloai, :ghichu)
    end
end

app/controllers/nccs_controller.rb
class NccsController < ApplicationController
  before_action :set_ncc, only: %i[ show edit update destroy ]

  # GET /nccs or /nccs.json
  def index
    @nccs = Ncc.all
  end

  # GET /nccs/1 or /nccs/1.json
  def show
  end

  # GET /nccs/new
  def new
    @ncc = Ncc.new
  end

  # GET /nccs/1/edit
  def edit
  end

  # POST /nccs or /nccs.json
  def create
    @ncc = Ncc.new(ncc_params)

    respond_to do |format|
      if @ncc.save
        format.html { redirect_to @ncc, notice: "Ncc was successfully created." }
        format.json { render :show, status: :created, location: @ncc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ncc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nccs/1 or /nccs/1.json
  def update
    respond_to do |format|
      if @ncc.update(ncc_params)
        format.html { redirect_to @ncc, notice: "Ncc was successfully updated." }
        format.json { render :show, status: :ok, location: @ncc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ncc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nccs/1 or /nccs/1.json
  def destroy
    @ncc.destroy
    respond_to do |format|
      format.html { redirect_to nccs_url, notice: "Ncc was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ncc
      @ncc = Ncc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ncc_params
      params.require(:ncc).permit(:macc, :tenncc, :diachi, :thongtin)
    end
end

app/controllers/sxes_controller.rb
class SxesController < ApplicationController
  before_action :set_sx, only: %i[ show edit update destroy ]

  # GET /sxes or /sxes.json
  def index
    @sxes = Sx.all
  end

  # GET /sxes/1 or /sxes/1.json
  def show
  end

  # GET /sxes/new
  def new
    @sx = Sx.new
  end

  # GET /sxes/1/edit
  def edit
  end

  # POST /sxes or /sxes.json
  def create
    @sx = Sx.new(sx_params)

    respond_to do |format|
      if @sx.save
        format.html { redirect_to @sx, notice: "Sx was successfully created." }
        format.json { render :show, status: :created, location: @sx }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sx.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sxes/1 or /sxes/1.json
  def update
    respond_to do |format|
      if @sx.update(sx_params)
        format.html { redirect_to @sx, notice: "Sx was successfully updated." }
        format.json { render :show, status: :ok, location: @sx }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sx.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sxes/1 or /sxes/1.json
  def destroy
    @sx.destroy
    respond_to do |format|
      format.html { redirect_to sxes_url, notice: "Sx was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sx
      @sx = Sx.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sx_params
      params.require(:sx).permit(:maSX, :tenHangs, :quocGia)
    end
end

app/controllers/thuocs_controller.rb
class ThuocsController < ApplicationController
  before_action :set_thuoc, only: %i[ show edit update destroy ]

  # GET /thuocs or /thuocs.json
  def index
    @thuocs = Thuoc.all
  end

  # GET /thuocs/1 or /thuocs/1.json
  def show
  end

  # GET /thuocs/new
  def new
    @thuoc = Thuoc.new
  end

  # GET /thuocs/1/edit
  def edit
  end

  # POST /thuocs or /thuocs.json
  def create
    @thuoc = Thuoc.new(thuoc_params)

    respond_to do |format|
      if @thuoc.save
        format.html { redirect_to @thuoc, notice: "Thuoc was successfully created." }
        format.json { render :show, status: :created, location: @thuoc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @thuoc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thuocs/1 or /thuocs/1.json
  def update
    respond_to do |format|
      if @thuoc.update(thuoc_params)
        format.html { redirect_to @thuoc, notice: "Thuoc was successfully updated." }
        format.json { render :show, status: :ok, location: @thuoc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @thuoc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thuocs/1 or /thuocs/1.json
  def destroy
    @thuoc.destroy
    respond_to do |format|
      format.html { redirect_to thuocs_url, notice: "Thuoc was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thuoc
      @thuoc = Thuoc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thuoc_params
      params.require(:thuoc).permit(:mathuoc, :TenThuoc, :MaHangSX, :MaNCC, :CongDung, :MaLoai, :GhiChu)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loai_thuocs_helper.rb
module LoaiThuocsHelper
end

app/helpers/nccs_helper.rb
module NccsHelper
end

app/helpers/sxes_helper.rb
module SxesHelper
end

app/helpers/thuocs_helper.rb
module ThuocsHelper
end

app/views/home/index.html.erb
<%= link_to 'Thuốc', 'thuocs#index' %> |
<%= link_to 'Nhà cung cấp', 'nccs#index' %> |
<%= link_to 'Loại thuốc', 'loai_thuocs#index' %> |
<%= link_to 'Hãng sản xuất', 'sxes#index' %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>New</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/loai_thuocs/_form.html.erb
<%= form_with(model: loai_thuoc) do |form| %>
  <% if loai_thuoc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loai_thuoc.errors.count, "error") %> prohibited this loai_thuoc from being saved:</h2>

      <ul>
        <% loai_thuoc.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :maloai %>
    <%= form.text_field :maloai %>
  </div>

  <div class="field">
    <%= form.label :tenloai %>
    <%= form.text_field :tenloai %>
  </div>

  <div class="field">
    <%= form.label :ghichu %>
    <%= form.text_area :ghichu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/loai_thuocs/edit.html.erb
<h1>Editing Loai Thuoc</h1>

<%= render 'form', loai_thuoc: @loai_thuoc %>

<%= link_to 'Show', @loai_thuoc %> |
<%= link_to 'Back', loai_thuocs_path %>

app/views/loai_thuocs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loai Thuocs</h1>

<table>
  <thead>
    <tr>
      <th>Maloai</th>
      <th>Tenloai</th>
      <th>Ghichu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loai_thuocs.each do |loai_thuoc| %>
      <tr>
        <td><%= loai_thuoc.maloai %></td>
        <td><%= loai_thuoc.tenloai %></td>
        <td><%= loai_thuoc.ghichu %></td>
        <td><%= link_to 'Show', loai_thuoc %></td>
        <td><%= link_to 'Edit', edit_loai_thuoc_path(loai_thuoc) %></td>
        <td><%= link_to 'Destroy', loai_thuoc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loai Thuoc', new_loai_thuoc_path %>

app/views/loai_thuocs/new.html.erb
<h1>New Loai Thuoc</h1>

<%= render 'form', loai_thuoc: @loai_thuoc %>

<%= link_to 'Back', loai_thuocs_path %>

app/views/loai_thuocs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Maloai:</strong>
  <%= @loai_thuoc.maloai %>
</p>

<p>
  <strong>Tenloai:</strong>
  <%= @loai_thuoc.tenloai %>
</p>

<p>
  <strong>Ghichu:</strong>
  <%= @loai_thuoc.ghichu %>
</p>

<%= link_to 'Edit', edit_loai_thuoc_path(@loai_thuoc) %> |
<%= link_to 'Back', loai_thuocs_path %>

app/views/nccs/_form.html.erb
<%= form_with(model: ncc) do |form| %>
  <% if ncc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ncc.errors.count, "error") %> prohibited this ncc from being saved:</h2>

      <ul>
        <% ncc.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :macc %>
    <%= form.text_field :macc %>
  </div>

  <div class="field">
    <%= form.label :tenncc %>
    <%= form.text_field :tenncc %>
  </div>

  <div class="field">
    <%= form.label :diachi %>
    <%= form.text_area :diachi %>
  </div>

  <div class="field">
    <%= form.label :thongtin %>
    <%= form.text_area :thongtin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nccs/edit.html.erb
<h1>Editing Ncc</h1>

<%= render 'form', ncc: @ncc %>

<%= link_to 'Show', @ncc %> |
<%= link_to 'Back', nccs_path %>

app/views/nccs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nccs</h1>

<table>
  <thead>
    <tr>
      <th>Macc</th>
      <th>Tenncc</th>
      <th>Diachi</th>
      <th>Thongtin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nccs.each do |ncc| %>
      <tr>
        <td><%= ncc.macc %></td>
        <td><%= ncc.tenncc %></td>
        <td><%= ncc.diachi %></td>
        <td><%= ncc.thongtin %></td>
        <td><%= link_to 'Show', ncc %></td>
        <td><%= link_to 'Edit', edit_ncc_path(ncc) %></td>
        <td><%= link_to 'Destroy', ncc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ncc', new_ncc_path %>

app/views/nccs/new.html.erb
<h1>New Ncc</h1>

<%= render 'form', ncc: @ncc %>

<%= link_to 'Back', nccs_path %>

app/views/nccs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Macc:</strong>
  <%= @ncc.macc %>
</p>

<p>
  <strong>Tenncc:</strong>
  <%= @ncc.tenncc %>
</p>

<p>
  <strong>Diachi:</strong>
  <%= @ncc.diachi %>
</p>

<p>
  <strong>Thongtin:</strong>
  <%= @ncc.thongtin %>
</p>

<%= link_to 'Edit', edit_ncc_path(@ncc) %> |
<%= link_to 'Back', nccs_path %>

app/views/sxes/_form.html.erb
<%= form_with(model: sx) do |form| %>
  <% if sx.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sx.errors.count, "error") %> prohibited this sx from being saved:</h2>

      <ul>
        <% sx.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :maSX %>
    <%= form.text_field :maSX %>
  </div>

  <div class="field">
    <%= form.label :tenHangs %>
    <%= form.text_field :tenHangs %>
  </div>

  <div class="field">
    <%= form.label :quocGia %>
    <%= form.text_field :quocGia %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sxes/edit.html.erb
<h1>Editing Sx</h1>

<%= render 'form', sx: @sx %>

<%= link_to 'Show', @sx %> |
<%= link_to 'Back', sxes_path %>

app/views/sxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sxes</h1>

<table>
  <thead>
    <tr>
      <th>Masx</th>
      <th>Tenhangs</th>
      <th>Quocgia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sxes.each do |sx| %>
      <tr>
        <td><%= sx.maSX %></td>
        <td><%= sx.tenHangs %></td>
        <td><%= sx.quocGia %></td>
        <td><%= link_to 'Show', sx %></td>
        <td><%= link_to 'Edit', edit_sx_path(sx) %></td>
        <td><%= link_to 'Destroy', sx, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sx', new_sx_path %>

app/views/sxes/new.html.erb
<h1>New Sx</h1>

<%= render 'form', sx: @sx %>

<%= link_to 'Back', sxes_path %>

app/views/sxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Masx:</strong>
  <%= @sx.maSX %>
</p>

<p>
  <strong>Tenhangs:</strong>
  <%= @sx.tenHangs %>
</p>

<p>
  <strong>Quocgia:</strong>
  <%= @sx.quocGia %>
</p>

<%= link_to 'Edit', edit_sx_path(@sx) %> |
<%= link_to 'Back', sxes_path %>

app/views/thuocs/_form.html.erb
<%= form_with(model: thuoc) do |form| %>
  <% if thuoc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thuoc.errors.count, "error") %> prohibited this thuoc from being saved:</h2>

      <ul>
        <% thuoc.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mathuoc %>
    <%= form.text_field :mathuoc %>
  </div>

  <div class="field">
    <%= form.label :TenThuoc %>
    <%= form.text_field :TenThuoc %>
  </div>

  <div class="field">
    <%= form.label :MaHangSX %>
    <%= form.text_field :MaHangSX %>
  </div>

  <div class="field">
    <%= form.label :MaNCC %>
    <%= form.text_field :MaNCC %>
  </div>

  <div class="field">
    <%= form.label :CongDung %>
    <%= form.text_field :CongDung %>
  </div>

  <div class="field">
    <%= form.label :MaLoai %>
    <%= form.text_field :MaLoai %>
  </div>

  <div class="field">
    <%= form.label :GhiChu %>
    <%= form.text_area :GhiChu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thuocs/edit.html.erb
<h1>Editing Thuoc</h1>

<%= render 'form', thuoc: @thuoc %>

<%= link_to 'Show', @thuoc %> |
<%= link_to 'Back', thuocs_path %>

app/views/thuocs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Thuocs</h1>

<table>
  <thead>
    <tr>
      <th>Mathuoc</th>
      <th>Tenthuoc</th>
      <th>Mahangsx</th>
      <th>Mancc</th>
      <th>Congdung</th>
      <th>Maloai</th>
      <th>Ghichu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thuocs.each do |thuoc| %>
      <tr>
        <td><%= thuoc.mathuoc %></td>
        <td><%= thuoc.TenThuoc %></td>
        <td><%= thuoc.MaHangSX %></td>
        <td><%= thuoc.MaNCC %></td>
        <td><%= thuoc.CongDung %></td>
        <td><%= thuoc.MaLoai %></td>
        <td><%= thuoc.GhiChu %></td>
        <td><%= link_to 'Show', thuoc %></td>
        <td><%= link_to 'Edit', edit_thuoc_path(thuoc) %></td>
        <td><%= link_to 'Destroy', thuoc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thuoc', new_thuoc_path %>

app/views/thuocs/new.html.erb
<h1>New Thuoc</h1>

<%= render 'form', thuoc: @thuoc %>

<%= link_to 'Back', thuocs_path %>

app/views/thuocs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mathuoc:</strong>
  <%= @thuoc.mathuoc %>
</p>

<p>
  <strong>Tenthuoc:</strong>
  <%= @thuoc.TenThuoc %>
</p>

<p>
  <strong>Mahangsx:</strong>
  <%= @thuoc.MaHangSX %>
</p>

<p>
  <strong>Mancc:</strong>
  <%= @thuoc.MaNCC %>
</p>

<p>
  <strong>Congdung:</strong>
  <%= @thuoc.CongDung %>
</p>

<p>
  <strong>Maloai:</strong>
  <%= @thuoc.MaLoai %>
</p>

<p>
  <strong>Ghichu:</strong>
  <%= @thuoc.GhiChu %>
</p>

<%= link_to 'Edit', edit_thuoc_path(@thuoc) %> |
<%= link_to 'Back', thuocs_path %>